document.getElementById('yourform').submit();
function linknama() {location.replace("/");}
function linkjudisuhu() {location.replace("https://judisuhu-comm.pages.dev/");}
function linktokekwin() {location.replace("http://gidx-tokek1.xyz/daftar?ref=babisexy");}
function linkpphoki() {location.replace("https://pphoki8899.xyz/?ref=babisexy");}
function linkaw8() {location.replace("https://www.aw8petir.com/id-id/register?refid=ymbrprab");}
function linkhoki177() {location.replace("https://halohoki177.com/register?ref=babisexy");}
function linknewliga365() {location.replace("https://newliga365vip.site/?action=register&rc=LEOK60YFBD&ci=11");}
function linklotto01() {location.replace("https://masterlotto01.org/referral/BABISEXY");}
function linkkijangwin() {location.replace("http://spiritkijangwin-1reff.shop/daftar?ref=babisexy");}
function linkaquaslot() {location.replace("https://aquaslot8.xyz/?ref=babisexy");}
function linkcoblos4d() {location.replace("https://usdc.coblosmau.xyz/?ref=babisexy");}
function linkkadobet() {location.replace("https://rodakadobet.com/?ref=babisexy");}
function linkmpo222() {location.replace("https://mpo222emas.com/register/JK86G0Y");}
function linkqqbos99() {location.replace("https://www.senisastra.com/Member/StreamlinedRegister?R=");}
function link303hoki() {location.replace("https://eworldexternal.com/register/B48RPJDN");}
function linkjet88bet() {location.replace("https://jet88enak.space/?ref=babisexy");}
function linkmpo369() {location.replace("https://mpo369bj.com/register/JQPK80KM");}
function link8bettingan() {location.replace("https://link1.bettingan.vip/");}
function linkmpo08() {location.replace("https://mpo08dna.xyz/register/Q2RDGN20");}
function linkmpo888() {location.replace("https://mpo888ind.com/register/437GR640");}
function linkdewatogel() {location.replace("https://dctws47490.dwtnaik.one/register?referral_code=babisexy");}

function linkwis77() {location.replace("https://secure.livechatinc.com/customer/action/open_chat?license_id=17110815&group=0");}
function linkmpo111() {location.replace("https://mpo111website.com/");}
function linkzona66() {location.replace("https://zona66.lol/");}
function linkgacorbos88() {location.replace("https://vip.gacorbos88uu.vip/");}
function linkyakinslot88() {location.replace("https://yakinslot88j.com/");}
function linkmusangwin() {location.replace("https://www.bermainmusangwin.com/");}
function linkdemen303() {location.replace("https://www.lavantgout.com/");}
function linknagatop() {location.replace("https://nagatopdice.xyz/");}
function linkjnt77() {location.replace("https://link02.aksesjnt777.com/");}
function linkfijislot() {location.replace("https://geovice.id/");}
function linkraja168() {location.replace("https://link10.raja168l.fit/");}
function linkmegabandar() {location.replace("https://megabandarmaxwin.xyz/");}
function linkbagus88() {location.replace("https://6.msbagus88.com/");}
function linkneo177() {location.replace("https://neo177berkumandang.com/");}
function linkkiw69() {location.replace("https://nottinghamathletics.com/");}
function linkmpo333() {location.replace("https://mpo333n.com/");}
function link66kone() {location.replace("https://66k.casa/");}
function linkrajampo() {location.replace("https://rajampo.io/");}
function linkamavi88() {location.replace("https://www.amavi88.com/");}
function linkbaron4d() {location.replace("https://baron5.xyz/");}
function linkmansion77() {location.replace("https://mansion77kui.store/");}
function linkjawara88() {location.replace("https://jawara88.co.za/");}
function linkmega38() {location.replace("https://mega38shop.com/");}
function linkgacor88() {location.replace("https://pastigacor88.cc/");}
function linksgpslot() {location.replace("https://mobile-sgpslot.com/");}
function linkmpo777() {location.replace("https://mpo777sultan.com/");}
function linkkingtoto() {location.replace("https://kingtotolive.icu/");}
function linkdewasloto() {location.replace("https://dewaslotomain.lol/");}
function linktwinbet() {location.replace("https://www.twinsbet.lt/");}
function linkw77() {location.replace("https://closetheskyoverukraine.com/");}
function linkajr88() {location.replace("https://ajr88.it.com/");}
function linkhoki178() {location.replace("https://log.hoki178dde.site/");}
function linkdewagacor77() {location.replace("https://beritabethel.com/");}
function linkkudapoker() {location.replace("https://daftarkudapoker.live/");}
function linkvipbet88() {location.replace("https://vipbet88bogor.com/");}
function linkpesiar88() {location.replace("https://pesiar88.com/");}
function linkpokerbo() {location.replace("https://pkbnibos.com/");}
function linkhoki138() {location.replace("https://hoki138stune.com/");}
function linktatabet() {location.replace("https://tatabet1125b.com/");}
function linksatutogel() {location.replace("https://satutogel.com/");}
function linkindogenting() {location.replace("https://indogenting1125c.com/");}
function linksupertogel() {location.replace("https://soccer.bungasepatubogor.com/");}
function linkslotmacau188() {location.replace("https://slotmacau188login.com/");}
function linkeraplay88() {location.replace("https://bekfb12728.eraplay88asli.us/");}
function linkjitu77() {location.replace("https://www.tooraretowear.org/");}
function linkkudetabet98() {location.replace("https://kudetabet98permainangacor.com/");}
function linkfungame777() {location.replace("https://cookiefungame777.net/");}
function linkm88() {location.replace("https://mfa-pmr.org/");}
function linkdafabet() {location.replace("https://m.dafabet.com/id");}
function linkrahayu88() {location.replace("https://rahayu88.me/");}
function linkagen288() {location.replace("https://agen288havefun.com/");}
function linkbk8() {location.replace("https://www.bk8idjp3.com/id-id/home");}
function linkjackpot168() {location.replace("https://vortexjackpot168.com/");}
function linktkp303() {location.replace("https://100tkp303.com/");}
function linkpentaslot() {location.replace("https://apenta28.sbs/");}
function linkgaza88() {location.replace("https://gaza20.sbs/");}
function linkcabe777() {location.replace("https://cabe777.com/");}
function linkneko9() {location.replace("https://neko9membara.com/web");}
function linkboss177() {location.replace("https://boss177loyal.com/web");}
function linkantiktoto() {location.replace("https://antiktoto.com/");}
function linkscbet88() {location.replace("https://kudahitam1.store/");}
function linksinggah4d() {location.replace("https://singgah4d.site/");}
function linkindoagen188() {location.replace("https://indoagent188.cv/");}
function linkapi77() {location.replace("https://cuan.api777sos.org/");}
function linkjoki55() {location.replace("https://jk55gscww.space/");}
function linknusabet() {location.replace("https://nusayuk.pics/");}
function linkmaxwin88() {location.replace("https://139.162.53.39/");}
function linktektok77() {location.replace("https://tektok77-tektok77.com/");}
function linkmarathonbet() {location.replace("https://www.marathonbet.com/in/");}
function link12bet() {location.replace("https://www.12aman.com/id");}
function link1xbet() {location.replace("https://1xlite-837593.top/");}
function linkshiokambing() {location.replace("https://manjurshiokambing.com/");}
function linkshiokambing2() {location.replace("https://mutiarasinar.com/");}
function linkshiokambing5() {location.replace("https://linesk5.com/web");}
function linkrajatoto3() {location.replace("https://rajatoto3ok.com/");}
function linkserbacasino() {location.replace("https://mejaserbacasino.vip/");}
function linkbom29toto() {location.replace("https://cbvu24dfyx.bom29paito.red/");}
function linkbetcoinasia() {location.replace("https://betcoinwin.me/");}
function linkkaikoslot() {location.replace("https://kaikoslot.news/");}
function linkmega55() {location.replace("https://link1.mega55indo.com/");}
function linkwishslot() {location.replace("https://wishslotofficial.net/");}
function linkpintutogel() {location.replace("https://pintutop.it.com/");}
function linknyaitogel() {location.replace("https://nyaitogelslot.com/");}
function linkaurajp() {location.replace("https://linkaurajp.info/");}
function linkdauntogel() {location.replace("https://xxxdaun.com/");}
function linkpiontogel() {location.replace("https://pionland.it.com/");}
function linkjadijp() {location.replace("https://jadijp7.com/");}
function linkcvtogel() {location.replace("https://cvtogel455.live/");}
function linkmpo555() {location.replace("https://mpo555-market.xyz/");}
function linkwisdom77() {location.replace("https://wisdom77gas.com/");}
function linkharbet35() {location.replace("https://harbetku.com/");}
function linkpoa88() {location.replace("https://poa88ok.com/");}
function linkkenzo188() {location.replace("https://worthitkenzo188.com/");}
function linklembagatoto() {location.replace("https://ws.lembagatotosolusi.org/");}
function linkroyal123() {location.replace("https://www.royal123gw.com/");}
function linkgacorslot() {location.replace("https://gel-al-simdii.com/");}
function linkagenslot168() {location.replace("https://sultanpizzashawarma.com/");}
function linkskslot() {location.replace("https://mantauterus.com/web");}
function linklotuspelangi() {location.replace("https://lotuseterna.gujarat.in/");}
function linkplaza4d() {location.replace("https://pasangsama.com/");}
function linkalexabet88() {location.replace("https://alexabet88t.net/");}
function linkdiva168() {location.replace("https://diva168xyz.com/");}
function linkmpo666() {location.replace("https://mpo666site.com/");}
function linkxuxu4d() {location.replace("https://xuxu4dijo.com/");}
function linkolympus188() {location.replace("https://olympus88url.com/");}
function linkrusia777() {location.replace("https://inirusia777.forum/");}
function linksbobet() {location.replace("https://www.sbobet.com/");}
function linksquad777() {location.replace("https://squad777team.org/");}
function linkhoki77() {location.replace("https://n77toto1.yachts/");}
function linkunoplay() {location.replace("https://uno1playbest.xyz/");}
function linkdewa234() {location.replace("https://www.clembrookchristmasfarm.com/");}
function linkjudi388() {location.replace("https://thehysteriacollective.com/");}
function link8togel() {location.replace("https://8togeltop.com/");}
function linkdewakoin() {location.replace("https://dewakoin05.com/");}
function linkkas138() {location.replace("https://vip1.kas138-oke.com/");}
function linkole777() {location.replace("https://m.991ole.com/");}
function link9win() {location.replace("https://9winpower5.pro/");}
function linkdewacasino() {location.replace("https://aulza13569.decaspro.xyz/");}
function linktongtoto() {location.replace("https://tongtotoratu.com/");}
function linkhokiwin() {location.replace("https://13.228.143.41/");}
function linkmpocasino() {location.replace("https://mpocasino-viva.com/");}
function linkolxtoto() {location.replace("https://duaempat11.olxtoto.io/");}
function linkratu89() {location.replace("https://ratu89.forum/");}
function link8bettingan() {location.replace("https://link4.bettingan.vip/");}
function linkmposport() {location.replace("https://mposportnine.com/");}
function linkmposlot() {location.replace("https://mposlotnew.xyz/");}
function linkmpopoker() {location.replace("https://nebulakkslot777.com/");}
function linkmpogacor() {location.replace("https://mpogacor-sip.com/");}
function linkmpo1221() {location.replace("https://mpo1221hall.net/");}
function linkmpo2121() {location.replace("https://depok2121.org/");}
function linkmpo1881() {location.replace("https://mpokuy1881.com/");}
function linkmpo88asia() {location.replace("https://mpo88asiaboom.com/");}
function linkmpo383() {location.replace("https://www.mpo383-bbb.com/");}
function linknexus88() {location.replace("https://www.xn--nexus-rt3ik37t.com/");}
function linkareabola() {location.replace("https://areabola.com/");}
function linkagenliga() {location.replace("https://agenliga.com/");}
function linkligabola() {location.replace("https://ligabola.com/");}
function linksukabet() {location.replace("https://sukabetlinkslotgacor.com/");}
function linkrajacuan() {location.replace("https://rcsatu.pro/");}
function linkdewi138() {location.replace("https://dewi138semangat.com/");}
function linkjoin999() {location.replace("https://join999.com/");}
function linkpari303() {location.replace("https://www.pari303.it.com/");}
function linkrajazeus() {location.replace("https://vvip1.rajazeus.fans/");}
function linksigma168() {location.replace("https://sigma168.com/");}
function linkjual303() {location.replace("https://jual303.com/");}
function linkpusatjudionline() {location.replace("https://maindipjo.store/");}
function linkkaratetoto() {location.replace("https://shimosato-farm.com/");}
function linkwatitoto() {location.replace("https://wati80215.com/");}
function linkrajamahjong() {location.replace("https://www.servergacor.rajamahjong.biz/");}
function linkhoki88bos() {location.replace("https://www.whistlestopdiners.com/");}
function linkmahjongjp88() {location.replace("https://mahjongjp88.net/");}
function linkolympus88() {location.replace("https://olympus88url.com/");}
function linkcupangjp() {location.replace("https://cupangjp.com/");}
function linkmurah4d() {location.replace("https://murah4dstellar.sbs/");}
function linkgacor69() {location.replace("https://sukasamasuka69.xyz/");}
function linkslot138() {location.replace("https://slot138playground.com/");}
function link888slot() {location.replace("https://888slot.com/");}
function linkpanen99() {location.replace("https://panen99verse.com/");}
function linkraja288() {location.replace("https://11.raja288l.top/");}
function linkmaxi188() {location.replace("https://maxi188.org/");}
function linkneymar88() {location.replace("https://neymar88.com/");}
function linkclickbet88() {location.replace("https://clickbet88bawaberkah.xyz/");}
function linkrajapanen() {location.replace("https://vendor.rajapanengacor.mom/");}
function linkoyoslot() {location.replace("https://t3t.oyoslot12.live/");}
function linkjudolbet88() {location.replace("https://judolbet88pp.com/");}
function linkslot123() {location.replace("https://www.solera.bar/");}
function linkdewagacor138() {location.replace("https://gg.dwgcr138.com/");}
function linkdewaslot88() {location.replace("https://slot828f.rest/");}
function linkdewa222() {location.replace("https://dewa222enak.com/");}
function linktuak88() {location.replace("https://maindituak.space/");}
function linktokyo77() {location.replace("https://tokyo77gcr11.site/");}
function linkapibet() {location.replace("https://apibetlogin.space/");}
function linkmaniakslot() {location.replace("https://maniakslot17.store/");}
function linkjoki288() {location.replace("https://joki288bk.info/");}
function linkgwinbola() {location.replace("https://gwinbolamid.com/");}
function linkyoyo88() {location.replace("https://yoyo88slot.online/");}
function linksarang777() {location.replace("https://agensarang.pro/");}
function linknagahoki88() {location.replace("https://www.girigramadarshini.com/");}
function linknvmslot898() {location.replace("https://nvmslot898.com/");}
function linkslotthailand() {location.replace("https://www.dscafeteria.com/");}
function linkkw303() {location.replace("https://vitafoamng.com/");}
function linkcumi787() {location.replace("https://2cumi787.click/");}
function linkterminal4d() {location.replace("https://terminal4dluccky.vip/");}
function linkrajajudi33() {location.replace("https://rajajudi33-login.com/");}








